server:
  port: ${PORT:8085}

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      routes:
      - id: account-service
        uri: http://localhost:8091
        predicates:
        - Path=/account/**
        filters:
        - RewritePath=/account/(?<path>.*), /$\{path}
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
      - id: customer-service
        uri: http://localhost:8092
        predicates:
        - Path=/customer/**
        filters:
        - RewritePath=/customer/(?<path>.*), /$\{path}
      - id: order-service
        uri: http://localhost:8090
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<path>.*), /$\{path}
      - id: product-service
        uri: http://localhost:8093
        predicates:
        - Path=/product/**
        filters:
        - RewritePath=/product/(?<path>.*), /$\{path}

#logging.level.io.github.resilience4j: DEBUG
#logging.level.org.springframework.cloud.gateway.filter.factory: TRACE
